### ISSUE TITLE
issue with python server side| tweet route

### ISSUE THREAD

**Issue by Jeffchiucp** [Jeffchiucp/Python-Tweet-Generator#7]
`@app.route('/tweet', methods=['POST'])
def tweet():
    body = json.loads(request.data)
    # noinspection PyBroadException
    try:
        twitter.tweet = tweets[body['tweet']]
        print(jsonify)
        return jsonify({
            "success": True
        })
    except Exception as e:
        print(jsonify)
        return jsonify({
            "success": False
        })
`

**Comment by Jeffchiucp** [comment]
Error log from Heroku Server
2017-10-16T22:53:09.907830+00:00 app[web.1]: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: tweet [SQL: 'SELECT tweet.id AS tweet_id, tweet.content AS tweet_content \nFROM tweet']

**Comment by Jeffchiucp** [comment]
![screen shot 2017-10-16 at 3 59 15 pm](https://user-images.githubusercontent.com/10523517/31638966-38ec57f2-b28b-11e7-9e35-375bf16f115b.png)

**Comment by Jeffchiucp** [comment]
Error: Shows Server 500 Error
![screen shot 2017-10-16 at 4 18 46 pm](https://user-images.githubusercontent.com/10523517/31639483-d40f8b3a-b28d-11e7-80df-ace7877c2a3f.png)

[Violation] 'load' handler took 1539ms

**Comment by Jeffchiucp** [comment]
Oct 17 21:37:58 shakespeare-tweet app/web.1:  [2017-10-18 04:37:58,427] ERROR in app: Exception on /favorites [GET] 
Oct 17 21:37:58 shakespeare-tweet app/web.1:  Traceback (most recent call last): 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      context) 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      cursor.execute(statement, parameters) 
Oct 17 21:37:58 shakespeare-tweet app/web.1:  sqlite3.OperationalError: no such table: tweet 
Oct 17 21:37:58 shakespeare-tweet app/web.1:  The above exception was the direct cause of the following exception: 
Oct 17 21:37:58 shakespeare-tweet app/web.1:  Traceback (most recent call last): 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      response = self.full_dispatch_request() 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      rv = self.handle_user_exception(e) 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      reraise(exc_type, exc_value, tb) 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      raise value 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      rv = self.dispatch_request() 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      return self.view_functions[rule.endpoint](**req.view_args) 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/app.py", line 125, in fav 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      tweets_list = Tweet.query.all() 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2703, in all 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      return list(self) 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__ 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      return self._execute_and_instances(context) 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      result = conn.execute(querycontext.statement, self._params) 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      return meth(self, multiparams, params) 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      return connection._execute_clauseelement(self, multiparams, params) 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      compiled_sql, distilled_params 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      context) 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      exc_info 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      reraise(type(exception), exception, tb=exc_tb, cause=cause) 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      raise value.with_traceback(tb) 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      context) 
Oct 17 21:37:58 shakespeare-tweet app/web.1:    File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute 
Oct 17 21:37:58 shakespeare-tweet app/web.1:      cursor.execute(statement, parameters) 
Oct 17 21:37:58 shakespeare-tweet app/web.1:  sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: tweet [SQL: 'SELECT tweet.id AS tweet_id, tweet.content AS tweet_content \nFROM tweet']

**Comment by Jeffchiucp** [comment]
I tried to create a Tweet table using SQL script that I wrote through the comand line:
https://stackoverflow.com/questions/9736085/run-a-postgresql-sql-file-using-command-line-arguments

**Comment by Jeffchiucp** [comment]
this ticket is closed, tweet API seems to be working well
