### ISSUE TITLE
issue with SQLite database (SQLAlchemy)

### ISSUE THREAD

**Issue by Jeffchiucp** [Jeffchiucp/Python-Tweet-Generator#8]
User cannot save their favorite tweet to the database hosted at Heroku
Terminal shows this error:
**sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: tweet [SQL: 'SELECT tweet.id AS tweet_id, tweet.content AS tweet_content \nFROM tweet']**

**Comment by Jeffchiucp** [comment]
Heroku log shows that there is database issue

2017-10-13T22:12:35.434820+00:00 app[web.1]: [2017-10-13 22:12:35,433] ERROR in app: Exception on /favorites [POST]
2017-10-13T22:12:35.434823+00:00 app[web.1]: Traceback (most recent call last):
2017-10-13T22:12:35.434824+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
2017-10-13T22:12:35.434825+00:00 app[web.1]:     context)
2017-10-13T22:12:35.434826+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
2017-10-13T22:12:35.434827+00:00 app[web.1]:     cursor.execute(statement, parameters)
2017-10-13T22:12:35.434827+00:00 app[web.1]: sqlite3.OperationalError: no such table: tweet
2017-10-13T22:12:35.434828+00:00 app[web.1]: 
2017-10-13T22:12:35.434829+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2017-10-13T22:12:35.434829+00:00 app[web.1]: 
2017-10-13T22:12:35.434830+00:00 app[web.1]: Traceback (most recent call last):
2017-10-13T22:12:35.434831+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
2017-10-13T22:12:35.434832+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-10-13T22:12:35.434833+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
2017-10-13T22:12:35.434833+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-10-13T22:12:35.434834+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
2017-10-13T22:12:35.434835+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-10-13T22:12:35.434835+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
2017-10-13T22:12:35.434836+00:00 app[web.1]:     raise value
2017-10-13T22:12:35.434837+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
2017-10-13T22:12:35.434837+00:00 app[web.1]:     rv = self.dispatch_request()
2017-10-13T22:12:35.434838+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
2017-10-13T22:12:35.434839+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-10-13T22:12:35.434839+00:00 app[web.1]:   File "/app/app.py", line 90, in fav
2017-10-13T22:12:35.434840+00:00 app[web.1]:     tweets_list = Tweet.query.all()
2017-10-13T22:12:35.434841+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2703, in all
2017-10-13T22:12:35.434842+00:00 app[web.1]:     return list(self)
2017-10-13T22:12:35.434842+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
2017-10-13T22:12:35.434843+00:00 app[web.1]:     return self._execute_and_instances(context)
2017-10-13T22:12:35.434843+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
2017-10-13T22:12:35.434844+00:00 app[web.1]:     result = conn.execute(querycontext.statement, self._params)
2017-10-13T22:12:35.434845+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
2017-10-13T22:12:35.434845+00:00 app[web.1]:     return meth(self, multiparams, params)
2017-10-13T22:12:35.434846+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
2017-10-13T22:12:35.434847+00:00 app[web.1]:     return connection._execute_clauseelement(self, multiparams, params)
2017-10-13T22:12:35.434847+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
2017-10-13T22:12:35.434848+00:00 app[web.1]:     compiled_sql, distilled_params
2017-10-13T22:12:35.434849+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
2017-10-13T22:12:35.434850+00:00 app[web.1]:     context)
2017-10-13T22:12:35.434850+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
2017-10-13T22:12:35.434851+00:00 app[web.1]:     exc_info
2017-10-13T22:12:35.434852+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
2017-10-13T22:12:35.434852+00:00 app[web.1]:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
2017-10-13T22:12:35.434853+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
2017-10-13T22:12:35.434854+00:00 app[web.1]:     raise value.with_traceback(tb)
2017-10-13T22:12:35.434855+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
2017-10-13T22:12:35.434855+00:00 app[web.1]:     context)
2017-10-13T22:12:35.434856+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
2017-10-13T22:12:35.434857+00:00 app[web.1]:     cursor.execute(statement, parameters)
2017-10-13T22:12:35.434862+00:00 app[web.1]: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: tweet [SQL: 'SELECT tweet.id AS tweet_id, tweet.content AS tweet_content \nFROM tweet']

**Comment by Jeffchiucp** [comment]
User can save their favorite tweet at the local host because we don't store it at the SQL database.
See the picture below that tweets are stored at the localhost:
![screen shot 2017-10-14 at 10 28 15 pm](https://user-images.githubusercontent.com/10523517/31582103-9ab33a12-b12f-11e7-80b4-c347af5f4ff2.png)

**Comment by Jeffchiucp** [comment]
Need help to create the SQL database Table, so user can Add Favorites Tweets.
I found some helpful link: http://pythoncentral.io/introductory-tutorial-python-sqlalchemy/

**Comment by Jeffchiucp** [comment]
Another option is to work around flask sql database using Postgres.
https://paultopia.github.io/posts-output/flask-heroku-postgres/

**Comment by Jeffchiucp** [comment]
I created a sql script that adds Tweet Table:
CREATE TABLE Tweet (
    tweet.id SERIAL,
    tweet.content VARCHAR(140)
);

**Comment by Jeffchiucp** [comment]
I got no error when perform the select queries at Heroku CL
shakespeare-tweet::DATABASE-> 'SELECT tweet.id AS tweet_id, tweet.content AS tweet_content \nFROM tweet'

**Comment by Jeffchiucp** [comment]
this ticket is updated as we remove the codes for SQLAlchemy and replace SQLite database with Postgres database. Close the issue
